### ISSUE TITLE
CTD's in Breezehome

### ISSUE THREAD

**Issue by DustyLeon** [ForgottenGlory/Living-Skyrim-3#354] opened 2021-05-17 14:15 UTC
**LS Version**
3.2.0

**Describe the bug**
I was going to post a minor bug report on the misplaced mannequins in Breezehome, but instead got two CTD's in a row. 

**To Reproduce**
Just walking around the home. First one happened after I equipped the mannequin (which fixes it's location), and the second happened a few moments after reloading. 

[Crash_2021_5_17_10-8-1.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494369/Crash_2021_5_17_10-8-1.txt)
[Crash_2021_5_17_9-53-43.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494370/Crash_2021_5_17_9-53-43.txt)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494372/saves.zip)

**Comment by ForgottenGlory** [comment] 2021-05-17 15:01
Yes, this is a duplicate of #343

**Closed as completed by ForgottenGlory** 2021-05-17 15:01 UTC
Labels: New Bug
