### ISSUE TITLE
Every time I read a skill book there's no notification that the particular skill improved

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#110] opened 2021-02-11 03:12 UTC
**LS Version**
3

**Describe the bug**
I've picked up a few skill books but the game never tells me that the skill improved.

**To Reproduce**
Pick up a skill book.

**Expected behavior**
A sound and notification is displayed saying the skill was improved.

**Screenshots**
n/a

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5962989/saves.zip)

**Comment by ForgottenGlory** [comment] 2021-02-11 03:17
Duplicate of #40

**Closed by ForgottenGlory** 2021-02-11 03:17 UTC
Labels: Dev Team, New Bug
