### ISSUE TITLE
Rugs Appearing Under Certain Follower's Feet

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#384] opened 2021-06-26 18:51 UTC
**LS Version**
3.2.3

**Describe the bug**
Certain followers, Cerri Steelfist in my case, have rugs appear under them when zone transitioning and inventory management. This appears to be related to when the followers were created vs backpacks from Campfire versioning as described in this post:

https://www.reddit.com/r/skyrimmods/comments/4qfybs/a_random_carpet_spawns_when_i_trade_items_with/?utm_source=amp&utm_medium=&utm_content=comments_view_all

Behavior is not seen with newer followers like Tocatta, and only happens when Campfire backpacks are equipped

**To Reproduce**
Recruit Cerri Steelfist, equip a Brown Fur Backpack to her "Let's trade items" inventory and transition through zones. This also happened with the vampire follower from Solitude inn.

**Expected behavior**
No rugs beneath feet

**Additional context**
Bear in mind I usually select "Let's crate an outfit" and just use standard option so I can remove their starting items. Not sure if this is relevant, first time seeing this bug since I almost always use Tocatta exclusively. It's happened with both a two follower party and three, but not on Tocatta herself (Cerri and Nylan or whatever his name is)

**Comment by ForgottenGlory** [comment] 2021-06-26 19:37
Duplicate of #375

**Closed as completed by ForgottenGlory** 2021-06-26 19:37 UTC
Labels: Duplicate
