### ISSUE TITLE
Giving Keiko Iron Arrows causes CTD.

### ISSUE THREAD

**Issue by Tychi101** [ForgottenGlory/Living-Skyrim-3#399] opened 2021-07-11 20:13 UTC
[Keiko Iron Arrow CTD.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6797593/Keiko.Iron.Arrow.CTD.zip)
**LS Version**
v3.3.0

**Describe the bug**
Giving Keiko (Follower) Iron Arrows after taking his nord hero arrows causes CTD.

**To Reproduce**
Steps to reproduce the behavior:  Give Keiko Iron Arrows

**Expected behavior**
No CTD.  

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

[Crash_2021_7_11_16-6-0.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6797589/Crash_2021_7_11_16-6-0.txt)
[Crash_2021_7_11_16-3-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6797590/Crash_2021_7_11_16-3-18.txt)
![2021-07-11 (2)](https://user-images.githubusercontent.com/87244234/125208838-ea451380-e262-11eb-9cda-34fad9960ab0.png)

**Comment by celadoneiron** [comment] 2021-07-12 08:34
Likely duplicate of #359.

**Closed as completed by celadoneiron** 2021-07-12 08:34 UTC
Labels: New Bug
