### ISSUE TITLE
Multiple CTD's in Bleak Falls Barrow

### ISSUE THREAD

**Issue by DustyLeon** [ForgottenGlory/Living-Skyrim-3#353] opened 2021-05-17 12:26 UTC
**LS Version**
3.2.0

**Describe the bug**
As per the title. I've had five CTD's throughout Bleak Falls Barrow, but this one seems the easiest to reproduce. 

**To Reproduce**
Just walking around. Both of the attached happened after going around to the chest in the back. 

**Additional context**
I already have UseOSAllocators set to 0. 

[Bleak Falls Barrow Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6493678/Bleak.Falls.Barrow.Save.zip)
[Crash_2021_5_17_8-7-0.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6493682/Crash_2021_5_17_8-7-0.txt)
[Crash_2021_5_17_8-15-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6493683/Crash_2021_5_17_8-15-6.txt)

**Comment by ForgottenGlory** [comment] 2021-05-17 12:30
Duplicate of #343

**Closed as completed by ForgottenGlory** 2021-05-17 12:30 UTC
Labels: Moderate Bug

**Comment by ForgottenGlory** [comment] 2021-05-17 13:08
Not a duplicate actually, but fixed 3.2.1 regardless
