### ISSUE TITLE
Breezehome

### ISSUE THREAD

**Issue by TheMrGeeBee** [ForgottenGlory/Living-Skyrim-3#433] opened 2021-07-26 11:52 UTC
**LS Version**
3.3

**Describe the bug**
Breezehome have some walls that shouldn't be there.

**To Reproduce**
Fresh install the list, enter Breezehome.

**Expected behavior**
No blocking walls

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 26 - 13 37 05 25](https://user-images.githubusercontent.com/43795491/126984332-4a503232-2854-4255-8668-573cf9129209.png)

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 26 - 13 37 16 93](https://user-images.githubusercontent.com/43795491/126984358-6d228d24-e8e4-499e-b9cc-bd575633c39a.png)

<img width="960" alt="The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 26 - 13 37 40 07" src="https://user-images.githubusercontent.com/43795491/126984376-9fbf274f-4f99-42fb-996d-283b5dd56f0e.png">

**Comment by ForgottenGlory** [comment] 2021-07-26 12:23
Duplicate of #391

**Closed as completed by ForgottenGlory** 2021-07-26 12:23 UTC
Labels: Duplicate
