### ISSUE TITLE
CTD North East of Skyrim (between Weynon Stones and Nightgate Inn)

### ISSUE THREAD

**Issue by Doverling321** [ForgottenGlory/Living-Skyrim-3#306] opened 2021-04-15 16:05 UTC
**LS Version**
Put the version of the list you are on here.
Living Skyrim 3.1.1

**Describe the bug**
CTD when exploring North East of Skyrim, happens approaching from Windhelm and from Dawnstar.

**To Reproduce**
Explore between Dawnstar and Windhelm, specifically around the Weynon Stones.

**Files**
[Crash_2021_4_15_16-52-4.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6319416/Crash_2021_4_15_16-52-4.txt)

**Comment by ForgottenGlory** [comment] 2021-04-18 20:23
Duplicate of #300

**Closed as completed by ForgottenGlory** 2021-04-18 20:23 UTC
Labels: New Bug
