### ISSUE TITLE
Ranger Outfit Craftables Need Value and/or Material Adjustments

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#502] opened 2021-08-20 16:31 UTC
**LS Version**
3.4.0.1

**Describe the bug**
Ranger Outfit craftables require near nothing to craft (1 Leather 1 Leather Strip), require no perk, and are available at 5 Smithing to craft. They all have a value of 1000 gold and can break early game economy for players. With cela's recent amazing sweep of the crafting list, I thought I'd submit this as another potential pitfall for the early game economy/new players. All of the other offenders seemed to be removed/adjusted by cela's work.

**To Reproduce**
Walk to a forge, instantly be rich.

**Expected behavior**
Enjoy the balanced economy that LS has otherwise (CACO, Trade & Barter, etc).

**Screenshots**
![20210818115159_1](https://user-images.githubusercontent.com/79347243/130264872-780f5b4c-e432-4de0-94ea-2889713f8e28.jpg)

**Comment by celadoneiron** [comment] 2021-08-20 23:47
Duplicate of #470 .

**Closed as completed by celadoneiron** 2021-08-20 23:47 UTC
Labels: New Bug
