### ISSUE TITLE
CTD's in Dragonsearch

### ISSUE THREAD

**Issue by DustyLeon** [ForgottenGlory/Living-Skyrim-3#355] opened 2021-05-17 14:57 UTC
**LS Version**
3.2.0

**Describe the bug**
I went back to a save from prior to purchasing Breezehome. Now it crashes either while walking around Dragonsearch or trying to leave. If these are all related to #343, I'll stop reporting them, but it's made the game unplayable. 

**To Reproduce**
Just walk around or try to exit. 

[Crash_2021_5_17_10-50-52.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494703/Crash_2021_5_17_10-50-52.txt)
[Crash_2021_5_17_10-41-23.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494704/Crash_2021_5_17_10-41-23.txt)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6494705/saves.zip)

**Comment by ForgottenGlory** [comment] 2021-05-17 15:01
Yes, this is a duplicate of #343

**Closed as completed by ForgottenGlory** 2021-05-17 15:01 UTC
Labels: New Bug
