### ISSUE TITLE
Follower gets hostile

### ISSUE THREAD

**Issue by Kiba94** [ForgottenGlory/Living-Skyrim-3#225] opened 2021-03-07 23:41 UTC
Most Recent Save: 
[Living Skyrim Follower Bug Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6098194/Living.Skyrim.Follower.Bug.Save.zip)

LS 3.0.1

The follower Uthgerd the Unbroken starts to attack me, when I try to click on her to talk. Also when I start combat with other enemys. Shes on the 2nd slot and the other 2 followers are Toccata(1st slot) and Inigo, they do not have this problem.

This same problem happened in back in Beta 5 with the follower Gorr. He also was on the third or second slot and the other followers had no problems at all.

![Uthgerd the Unbroken Screenshot](https://user-images.githubusercontent.com/79775391/110259497-3e37a700-7fa8-11eb-938d-8a8c6393e850.jpg)

[Living Skyrim Follower Bug Video.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6098204/Living.Skyrim.Folower.Bug.zip)

**Comment by lukefly2** [comment] 2021-03-08 15:56
uhh this isn't super related to your problem, but you shouldn't have inigo in the follower framework. He has his own AI and breaks if you add him to the framework.

**Comment by Kiba94** [comment] 2021-03-08 17:18
> uhh this isn't super related to your problem, but you shouldn't have inigo in the follower framework. He has his own AI and breaks if you add him to the framework.

I edited it in the post, you are right, he has no slot. I did not add him into the follower framework, he isn't in there

**Comment by lukefly2** [comment] 2021-03-08 17:22
oh ok i just wanted to make sure that the issue wasn't related/caused by that

**Comment by ForgottenGlory** [comment] 2021-03-17 20:32
Related to/duplicate of #211

**Closed by ForgottenGlory** 2021-03-17 20:32 UTC
Labels: Dev Team, Minor Bug
