### ISSUE TITLE
Door in Mixwater Mill is standing in a field

### ISSUE THREAD

**Issue by Weedy2503** [ForgottenGlory/Living-Skyrim-3#153] opened 2021-02-20 12:24 UTC
There is a door to a workers house in the middle of a field in mixwater mill

Name:

Base form ID: 00012EB1
Base Type: DOOR (Door)
Ref form ID: 0001656B
Form location information: [6]:
Position: [6]:
Model: FarmhouseDoor01.nif [3]:

LS3 Beta 3

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment] 2021-02-21 00:27
Duplicate of #136

**Closed by ForgottenGlory** 2021-02-21 00:27 UTC
Labels: Dev Team, New Bug
