### ISSUE TITLE
Purple Trunked Trees near Reachwind Eyrie

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#120] opened 2021-02-11 15:52 UTC
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Bate 3

**Describe the bug**
On the cliff across from Reachwind Eyrie there are trees with purple trunks. They are across the ravine to the east of Reachwind Eyrie, along the cliff side. If one approaches the trees their trunks turn to normal tree trunks, but if one backs away they revert to purple.

**To Reproduce**
Travel south to Reachwind Eyrie, as you approach the tower's front, turn right (east) and look from the cliff, across the ravine there will be purple trucked trees on the cliff. They will turn normal if approached but will revert back when one walks a distance away.

**Expected behavior**
Trees to have normal colored tree trucks, not shiny purple.

**Screenshots**
![2021-02-11 (8)](https://user-images.githubusercontent.com/78520661/107661273-600e6a00-6c46-11eb-908e-9a7739ad9053.png)

**Additional context**
N/A

**Comment by ForgottenGlory** [comment] 2021-02-11 15:54
Duplicate of #9

**Closed by ForgottenGlory** 2021-02-11 15:54 UTC
Labels: Dev Team, New Bug
