### ISSUE TITLE
Hedge Mage Armor Texture transparent

### ISSUE THREAD

**Issue by idefelipe** [ForgottenGlory/Living-Skyrim-3#29] opened 2021-02-02 07:40 UTC
**LS Version**
LS3

**Describe the bug**
When I dress the Hedge Armor Set to the character body and hair and hands and boots are dissapeared.

**To Reproduce**
1. Start a new game
2. No modifications in character creation (Nord, Male, no changes)
3. Start in Sleeping Giang Inn (riverwood)
4. Get out of the Inn
5. Dress the Hedge armor set
6. See picture attached.

**Expected behavior**
It should show the armour set dressed.

**Screenshots**
https://i.imgur.com/PKNH045.jpg

**Additional context**
I have tested it with Rudy's ENB and Re-Engaged ENB, and it happens in both cases.

**Comment by ForgottenGlory** [comment] 2021-02-02 17:07
Duplicate of #6

**Closed by ForgottenGlory** 2021-02-02 17:07 UTC
Labels: Dev Team, New Bug
