### ISSUE TITLE
Temple of Stendarr Female Models go brrrr

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#367] opened 2021-05-25 23:31 UTC
**LS Version**
3.2.1

**Describe the bug**
Female NPC models have very weird geometry when moving around. In particular the one in the screenshots I am about to submit.

**To Reproduce**
resetai on the NPC and watch as she stands up and her tits pop through her back, then warp all over as she stands upright. She goes to sit down and her tits appear to glide up into her neck/face.

**Expected behavior**
Normal-ass tiddies

**Screenshots**
![SkyrimSE 2021-05-25 16-26-24](https://user-images.githubusercontent.com/82478190/119581046-a52e5600-bd76-11eb-8359-a317ba0d1774.png)
![SkyrimSE 2021-05-25 16-26-21](https://user-images.githubusercontent.com/82478190/119581052-a65f8300-bd76-11eb-8aef-1e0322627cc9.png)
![SkyrimSE 2021-05-25 16-26-05](https://user-images.githubusercontent.com/82478190/119581054-a790b000-bd76-11eb-9264-bb0253552f9f.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
(  .  Y  .  )

**Comment by celadoneiron** [comment] 2021-05-25 23:48
Duplicate of #366

**Closed as completed by celadoneiron** 2021-05-25 23:48 UTC
Labels: New Bug
