### ISSUE TITLE
Staff of flames has no 3rd person appearance

### ISSUE THREAD

**Issue by Gerdofal** [ForgottenGlory/Living-Skyrim-3#398] opened 2021-07-11 18:21 UTC
**LS Version**
3.3

**Describe the bug**
Staff of flames functions as expected in combat, but has no 3rd person appearance. It does have a minor "heat" effect where the end of the staff should be, but no staff itself. In 1st person, it works just fine.

**To Reproduce**
Looted staff off npc and equipped

**Expected behavior**
Staff should have a staff appearance in both 1st and 3rd person

**Screenshots**

![No 3rd person staff](https://user-images.githubusercontent.com/6471848/125205970-2d868e80-e231-11eb-9e8f-1889b1b23b03.png)

(Note the tiny ball of fire you see with the pine tree behind it)

I tried but was unable to get any kind of id for the staff, it just can't be clicked in 3rd person or 1st person view. Here is how it looks in inventory

![Staff inventory](https://user-images.githubusercontent.com/6471848/125206060-9ec64180-e231-11eb-9c34-3e911f269a3a.png)

**Comment by Gerdofal** [comment] 2021-07-11 18:27
New information I noticed as I was running around. The staff does actually have an appearance, it's just in the wrong place.  Still not clickable, clicking the staff always selects the PC instead.  Staff is always at the feet of the player, oriented with facing, flat to ground, regardless if in combat mode or sheathed.  If the ground is not perfectly level, the staff is underground and not visible.

![Staff ground](https://user-images.githubusercontent.com/6471848/125206186-53f8f980-e232-11eb-8a77-23e8f5722a63.png)

**Comment by ForgottenGlory** [comment] 2021-07-11 19:04
Duplicate of #394

**Closed as completed by ForgottenGlory** 2021-07-11 19:04 UTC
Labels: New Bug
