### ISSUE TITLE
NPC Conflict

### ISSUE THREAD

**Issue by Jarendron** [ForgottenGlory/Living-Skyrim-3#333] opened 2021-05-05 14:47 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.2.0

**Describe the bug**
The outpost tower in riften near shor's stone there is a Dremora hosting a party with a few Revelers. The NPCs will begin fighting eachother when you begin a new game.

**To Reproduce**
If you choose to start the game as an outlaw, you will spawn in that tower along with a few bandits. 

**Expected behavior**
The NPC's shouldn't be fighting.

**Screenshots**

![07](https://user-images.githubusercontent.com/83714085/117160328-40d33480-ad7e-11eb-9695-cdd509350504.jpg)
![00](https://user-images.githubusercontent.com/83714085/117160331-416bcb00-ad7e-11eb-81d7-330ce01ad7c1.jpg)
![01](https://user-images.githubusercontent.com/83714085/117160333-42046180-ad7e-11eb-9e45-29ff5214ea3a.jpg)
![02](https://user-images.githubusercontent.com/83714085/117160334-429cf800-ad7e-11eb-8ca2-046716dbc920.jpg)
![03](https://user-images.githubusercontent.com/83714085/117160336-43358e80-ad7e-11eb-9382-13327397516a.jpg)
![04](https://user-images.githubusercontent.com/83714085/117160338-43ce2500-ad7e-11eb-893a-9b918d471bd3.jpg)
![05](https://user-images.githubusercontent.com/83714085/117160340-4466bb80-ad7e-11eb-8065-70fdf45cfb46.jpg)
![06](https://user-images.githubusercontent.com/83714085/117160346-4597e880-ad7e-11eb-976c-efb91a2a1d4e.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment] 2021-05-15 16:00
On the one hand, this is the list functioning as intended, but on the other this is kinda odd. Technically not a bug, but I'll look into it eventually.

**Comment by ForgottenGlory** [comment] 2021-07-08 20:01
Should be fixed 3.3.0

**Closed as completed by ForgottenGlory** 2021-07-08 20:01 UTC
Labels: Intended, Reminder
