### ISSUE TITLE
Crash to desktop outside Loreius farm 

### ISSUE THREAD

**Issue by itzrabiid** [ForgottenGlory/Living-Skyrim-3#305] opened 2021-04-14 07:56 UTC
[Game Saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6309119/Game.Saves.zip)

**LS Version**
Living Skyrim 3.1.1

**Describe the bug**
Crash to desktop outside Loreius Farm while fighting wolves.

**To Reproduce**
Continue straight ahead and fight the wolves

**Expected behavior**
To not crash
[Crash_2021_4_14_18-4-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6309019/Crash_2021_4_14_18-4-6.txt)

**Screenshots**
![Map Screenshot](https://user-images.githubusercontent.com/70617000/114674377-44fdca80-9d5b-11eb-8972-0cc9c49c37c5.jpg)

**Additional context**
The crash was replicated 3 times, hope its an easy fix.

**Comment by ForgottenGlory** [comment] 2021-04-18 20:24
Duplicate of #300

**Closed as completed by ForgottenGlory** 2021-04-18 20:24 UTC
Labels: New Bug
