### ISSUE TITLE
CTD Approaching Korvanjund NE of Whiterun

### ISSUE THREAD

**Issue by mcilduff** [ForgottenGlory/Living-Skyrim-3#309] opened 2021-04-16 16:02 UTC
[Crash_2021_4_16_23-48-15.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6326419/Crash_2021_4_16_23-48-15.txt)
[Crash_2021_4_16_23-28-35.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6326420/Crash_2021_4_16_23-28-35.txt)
[Crash_2021_4_16_23-22-7.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6326421/Crash_2021_4_16_23-22-7.txt)

LS Version
v3.1.1

Describe the bug
Crash to Desktop approaching Korvanjund.

To Reproduce
Approach Korvanjund from north-east of Whiterun.

Expected behavior
Not to CTD.

Screenshots
![CTD](https://user-images.githubusercontent.com/82669045/115051840-d4e47580-9f0f-11eb-8852-149610597b83.png)

Additional context
Replicated crash 4 times.

**Comment by ForgottenGlory** [comment] 2021-04-18 20:24
Duplicate of #300

**Closed as completed by ForgottenGlory** 2021-04-18 20:24 UTC
Labels: New Bug
