### ISSUE TITLE
ctd on the road from Markarth to dushnikh yal

### ISSUE THREAD

**Issue by BigStipiThe7th** [ForgottenGlory/Living-Skyrim-3#383] opened 2021-06-24 08:01 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
first crashlog
[Crash_2021_6_24_16-52-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6707083/Crash_2021_6_24_16-52-18.txt)

second crashlog
[Crash_2021_6_24_17-28-55.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6707245/Crash_2021_6_24_17-28-55.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save368_8ABE392D_0_486164686F64_Tamriel_020419_20210624025803_21_1.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6707391/Save368_8ABE392D_0_486164686F64_Tamriel_020419_20210624025803_21_1.txt)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
 3.2.2

**Describe the bug**
on the way to dushnikh yal from markarth, you cross over a little bridge next to where the khajit camp can be,
past the bridge is a right turn which leads to dushnikh yal, if i go a little bit down that road to dushnikh yal the game crashes to the desktop.. And the game will eventually crash even if i stand by the road (road to dushnikh yal) for awhile (10-15 seconds)

**To Reproduce**
Walk from the gates of markarth all the way down to the right turn that leads to dushnikh yal and it will either instantly crash if i go down the road or it will eventually crash if i stand by the road for about 10-15 seconds 

**Expected behavior**
for the game to not ctd on the way to dushnikh yal

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
there is no npcs on the road 

this is the first time ive done a bug report so if i have done or sent anything incorrect, that is the reason.

**Comment by ForgottenGlory** [comment] 2021-07-04 02:00
Duplicate of #357 Fixed 3.3.0

**Closed as completed by ForgottenGlory** 2021-07-04 02:00 UTC
Labels: Duplicate, Moderate Bug
