### ISSUE TITLE
Crash to Windows

### ISSUE THREAD

**Issue by cmm093** [ForgottenGlory/Living-Skyrim-3#325] opened 2021-05-02 04:20 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash_2021_5_1_22-16-26.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6410721/Crash_2021_5_1_22-16-26.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**
_I tried to find the save file in the Documents folder, and I can see where the save folder is located, but it's empty. I found a folder in the Profiles section of the Living Skyrim folder with a saves folder, so I'll link both of the most recent files on google drive here:_
https://drive.google.com/file/d/1bqQwyJDJhmlfInQFQZVDfL3G6gx52DgR/view?usp=sharing
https://drive.google.com/file/d/1kYugKHT7OW1ndzXDliEfJiVeuMjzi9QN/view?usp=sharing
_I hope these help._

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
_version: 3.1.1_

**Describe the bug**
_When traveling down the path in the direction the player is facing, toward the objective, the game crashes to windows consistently._

**To Reproduce**
_Travel down the path in the direction the player is facing toward the quest objective indicated on the map. I saved relatively close to the crash point, so it shouldn't take more than a few seconds of travel time to crash again if all variable are reproduced._

**Expected behavior**
_I expect a crash to windows._

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

Full transparency: I had installed 1 other mod, the perk point book mod.
Here's a nexus link: https://www.nexusmods.com/skyrimspecialedition/mods/2254
I have reproduced the crash after uninstalling the mod, and I don't believe it has anything to do with this mod. No other alterations were made.
I understand if you don't want to look at this report because of this; however, I genuinely believe the issue isn't at all connected.
If requested, I can start a new save file without the mod and run the game to that point and see if the crash persists.

On a personal note, I want to thank you guys for all you do. You've put together an amazing project, and I look forward to seeing where it goes in the future.

**Comment by ForgottenGlory** [comment] 2021-05-02 04:35
Duplicate of #300 , fixed 3.2.0

**Closed as completed by ForgottenGlory** 2021-05-02 04:35 UTC
Labels: New Bug
