### ISSUE TITLE
CTD in Ustengrav and Shroud Hearth Barrow

### ISSUE THREAD

**Issue by chirpingbird** [ForgottenGlory/Living-Skyrim-3#350] opened 2021-05-16 00:34 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

I was crashing to desktop in Shroud Hearth Barrow repeatedly, not in the exact same place but I'd load a save, take a few steps maybe loot something and crash again. I gave up and left that location. Now I'm in Ustengrav and the same behavior is happening.

Attaching last 3 crash logs and saves.
[Crash_2021_5_15_11-17-11.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6488431/Crash_2021_5_15_11-17-11.txt)
[Crash_2021_5_15_11-23-22.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6488432/Crash_2021_5_15_11-23-22.txt)
[Crash_2021_5_15_18-9-50.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6488433/Crash_2021_5_15_18-9-50.txt)

Had trouble attaching the saves so put copies into dropbox here:

https://www.dropbox.com/sh/htcg49kk2s44tvk/AAC0zyccxuEKGUT9rgvlU3Hya?dl=0

I'm new to github and bug reporting on this kind of project so please let me know if there's anything else you need.

**Comment by chirpingbird** [comment] 2021-05-16 23:31
Also occurring in High Gate Ruins.

[Crash_2021_5_16_14-46-46.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6490253/Crash_2021_5_16_14-46-46.txt)
[Crash_2021_5_16_19-24-44.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6490254/Crash_2021_5_16_19-24-44.txt)

**Comment by ForgottenGlory** [comment] 2021-05-17 12:32
Duplicate of #343

**Closed as completed by ForgottenGlory** 2021-05-17 12:32 UTC
Labels: New Bug
