### ISSUE TITLE
One-way wall in Embershard Mine

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#72] opened 2021-02-06 04:13 UTC
**LS Version**
LS3 Beta 2

**Describe the bug**
In Embershard mine, the small treasure room about halfway through the dungeon has a wall that is invisible from one side. Walking into the wall results in a clipping error that requires the use of `tcl` to escape.

**To Reproduce**
1. Enter Embershard mine
2. Proceed through the dungeon taking the "vanilla" route, lowering the drawbridge and crossing
3. Once across, look through the gap in the wall to the right. Note that there is a wall visible where the gate would normally be
4. Proceed around the corner and note that the gate is there and the chest is visible -- there is no wall
5. Pick the lock and proceed through the gate
Result: Stuck in an invisible wall. Must TCL to get out

**Screenshots**
https://imgur.com/a/aXCq6sk

**Comment by ForgottenGlory** [comment] 2021-02-09 17:57
Duplicate of #17

**Closed by ForgottenGlory** 2021-02-09 17:57 UTC
Labels: Dev Team, Moderate Bug
