### ISSUE TITLE
Crash upon walking into area surrounding Nightgate Inn

### ISSUE THREAD

**Issue by mully2229** [ForgottenGlory/Living-Skyrim-3#311] opened 2021-04-18 20:23 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

[Crash_2021_4_18_20-36-32.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6332078/Crash_2021_4_18_20-36-32.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Crash Saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6332126/Crash.Saves.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3.1.1

**Describe the bug**
Game CTD when entering area surrounding the Nightgate Inn 

**To Reproduce**
Walking into the area from the western and eastern roads cause a crash. Easy to reproduce by simply walking over the small hill path in the screenshot below.

**Expected behavior**
To not crash

**Screenshots**

![enb2021_4_18_20_58_20](https://user-images.githubusercontent.com/82778396/115159529-793ef700-a08b-11eb-8e89-201dc2148347.jpeg)
![enb2021_4_18_20_58_36](https://user-images.githubusercontent.com/82778396/115159533-7e03ab00-a08b-11eb-8654-f4e09ae3229d.jpeg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment] 2021-04-18 20:23
Duplicate of #300

**Closed as completed by ForgottenGlory** 2021-04-18 20:23 UTC
Labels: New Bug
