### ISSUE TITLE
Big glowing sphere around light sources in Markarth

### ISSUE THREAD

**Issue by Nawh** [ForgottenGlory/Living-Skyrim-3#204] opened 2021-03-04 01:30 UTC
**LS Version**
LS3 3.0.0

**Describe the bug**
Big glowing sphere around some light sources in Markarth.

Seems to be related to DynDOLOD (and maybe Lantern Of Skyrim II) : no sphere when i disable "DynDOLOD Output" in MO2 

**To Reproduce**
Enter to Markarth.

**Expected behavior**
Markarth without big glowing sphere.

**Screenshots**
![Screenshot_516](https://user-images.githubusercontent.com/29104754/109893892-c78b6880-7c8c-11eb-94b3-1488aa371f83.png)

**Comment by mojucy** [comment] 2021-03-04 04:17
Same issue, can confirm it seems to be dyndolod related due to markarth being it's own world space from what I've read, and it doesn't happen elsewhere to my knowledge. Disabling enb seems to get rid if it temporarily, but no matter the enbs I've tried, or the settings I've changed within (clickable on or off settings primarily) have resolved it besides turning my enb off. I havent tried disabling dyndolod or tweaking it as I have no clue what I'm doing in that department. 
![20210303_195123](https://user-images.githubusercontent.com/79695268/109910677-aa4b9f80-7c76-11eb-9bcc-edef58b837f1.jpg)

**Comment by tjbassoon** [comment] 2021-03-16 23:15
FWIW I've had this happen in other load orders built from scratch.

**Comment by TwistedModding** [comment] 2021-03-18 17:24
enb light patcher might be able to fix this.

**Comment by ForgottenGlory** [comment] 2021-03-20 11:47
This is caused by the child lights option in DynDOLOD, Markarth for whatever reason is a "world" on the same hierarchy level as Tamriel so it gets these generated. I'm unsure if I'm going to fix this for 3.1.0 as it does require regenerating DynDOLOD and such. Alternatively, we can make a patch that just disables these light orbs.

**Comment by mojucy** [comment] 2021-03-20 13:15
There are a few more than those if you're going to patch it. One in a mine in the city for example. I havent been on in a while to provide the example, those are the 3 most obvious as its apparent upon entering the city. Not sure if there are more than the one in the mine (or just outside the entrance I dont quite remember). Whatever is easier for you. It's not game breaking, just jarring. Nbd, just thought I did something wrong at first.

**Comment by ForgottenGlory** [comment] 2021-03-21 12:06
This will be fixed eventually, just not for 3.1.0

**Comment by ForgottenGlory** [comment] 2021-05-01 14:38
Fixed 3.2.0

**Closed by ForgottenGlory** 2021-05-01 14:38 UTC
Labels: Minor Bug
