### ISSUE TITLE
Alchemy perks

### ISSUE THREAD

**Issue by TheMapzor** [ForgottenGlory/Living-Skyrim-3#342] opened 2021-05-09 17:15 UTC
**LS Version**
3.2.0.

**Describe the bug**
A couple of rank 2 perks on the alchemy tree cannot be obtained, specifically r2 slow metabolism and r2 concentrated poison, I would believe due to something wrong in the level requirements (in game it says "70, 1" and "90, 1" rather than just 70 and 90).

**To Reproduce**
attempt to obtain aforementioned perks.

**Expected behavior**
for said perks to be obtainable

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment] 2021-05-12 15:39
Duplicate of #326

**Closed as completed by ForgottenGlory** 2021-05-12 15:39 UTC
Labels: Duplicate
