### ISSUE TITLE
embershard mine 

### ISSUE THREAD

**Issue by vMichaelMyersv** [ForgottenGlory/Living-Skyrim-3#92] opened 2021-02-08 09:13 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
latest

**Describe the bug**
when entering the loot cell in the middle of the dungeon a stone wall spawns behind you stopping you from leaving had to use tcl to get out 

**To Reproduce**
go inside loot cell

**Expected behavior**
no wall to appear trapping you inside 

**Screenshots**
![enb2021_2_8_09_05_32](https://user-images.githubusercontent.com/78704848/107199107-e5e3a880-69ed-11eb-81ea-ce50fa2c8436.jpg)
![enb2021_2_8_09_06_12](https://user-images.githubusercontent.com/78704848/107199113-e9772f80-69ed-11eb-8e31-72c2f2396aa6.jpg)

**Additional context**

**Comment by TwistedModding** [comment] 2021-02-08 17:28
duplicate of #72

**Closed by TwistedModding** 2021-02-08 17:28 UTC
Labels: Dev Team, New Bug
