### ISSUE TITLE
Purple Trees around Mixwater Mill

### ISSUE THREAD

**Issue by Weedy2503** [ForgottenGlory/Living-Skyrim-3#154] opened 2021-02-20 23:11 UTC
There are purple Trees around Mixwater Mill which load the missing texture if you get close enough and unload them when you go a little bit further away. Ignore the Object selected in the screenshot, when you look past it you can see a purple tree in the distance

Name:

Base form ID: AE08856D
Base Type TREE (Tree)
Ref form ID: AE08856E
Form location information: [6]:
Position: [6]:
Model: gkbcyrodil3.nif [3]:

--------

GKB Cyrodil 04
Base defined in: Treeswinedave.esp
Base last changed by: Treeswinedave.esp
Ref defined in: Treeswinedave.esp
Ref last changed by: Treeswinedave.esp

LS3 Beta 3

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
![image](https://user-images.githubusercontent.com/79363318/108610867-713f3f80-73d9-11eb-915d-44ed795e1daf.jpeg)

**Comment by ForgottenGlory** [comment] 2021-02-21 00:26
Duplicate of #9

**Closed by ForgottenGlory** 2021-02-21 00:26 UTC
Labels: Dev Team, New Bug
