### ISSUE TITLE
Floating Door #?

### ISSUE THREAD

**Issue by Orc12x** [ForgottenGlory/Living-Skyrim-3#107] opened 2021-02-10 23:59 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest release

**Describe the bug**
A door floating in the air

**To Reproduce**
look above the closest Giant camp to Whiterun

**Expected behavior**
Doors do not float in the air ❌ 

**Screenshots**
https://ibb.co/2WZDQ8z

**Additional context**

**Comment by TwistedModding** [comment] 2021-02-11 00:06
Fixed, esp in patch channel

**Comment by ForgottenGlory** [comment] 2021-02-11 00:16
Duplicate of #63

**Closed by ForgottenGlory** 2021-02-11 00:16 UTC
Labels: Dev Team, New Bug
