### ISSUE TITLE
Blackface Forsworn

### ISSUE THREAD

**Issue by AvnarJakob** [ForgottenGlory/Living-Skyrim-3#143] opened 2021-02-17 12:47 UTC
**LS Version**
3

**Describe the bug**
I found a few Forsworn (Breton and Nord) with black faces at Deepwood Redoubt on the border between Haafingar and the Reach

**To Reproduce**
Fast travel to Deepwood Redoubt

**Expected behavior**
White Faces

![20210217133743_1](https://user-images.githubusercontent.com/75129695/108206581-dddee380-7126-11eb-99e6-dfbeda2570be.jpg)
![20210217133750_1](https://user-images.githubusercontent.com/75129695/108206584-dfa8a700-7126-11eb-8511-4e2142a7e99f.jpg)

[Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5995725/Save.zip)

**Comment by ForgottenGlory** [comment] 2021-02-17 23:13
Duplicate of #32

**Closed by ForgottenGlory** 2021-02-17 23:13 UTC
Labels: Dev Team, New Bug
