### ISSUE TITLE
Colliding/Stacked buildings in Falkreath 

### ISSUE THREAD

**Issue by BryanBoru** [ForgottenGlory/Living-Skyrim-3#221] opened 2021-03-06 23:04 UTC
[Falkreath.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6096056/Falkreath.zip)
If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
3.0.1

**Describe the bug**
Overlapping buildings, gates and objects in Falkreath

**To Reproduce**
Completely stock 3.0.1 installation through Wabbajack, Start as Imperial Soldier in army, go to Falkreath

**Expected behavior**
all buildings in town being normal to path into

**Screenshots**

Floating NPC
![20210306175430_1](https://user-images.githubusercontent.com/9432488/110224043-56270200-7ea6-11eb-9e70-cb9aad51d845.jpg)
a useless smelter
![20210306175444_1](https://user-images.githubusercontent.com/9432488/110224044-57582f00-7ea6-11eb-9c56-98fee319bfc9.jpg)
Unable to enter this one
![20210306175457_1](https://user-images.githubusercontent.com/9432488/110224046-57f0c580-7ea6-11eb-861c-69dd5ca71e69.jpg)
A Double Gate
![20210306175517_1](https://user-images.githubusercontent.com/9432488/110224047-58895c00-7ea6-11eb-8655-3fe12d61c1e6.jpg)
Unable to get through
![20210306175735_1](https://user-images.githubusercontent.com/9432488/110224049-5921f280-7ea6-11eb-85ff-8ff4ae62dd61.jpg)
A different Double Gate
![20210306175820_1](https://user-images.githubusercontent.com/9432488/110224050-59ba8900-7ea6-11eb-849d-b4584710f9e6.jpg)
![20210306175830_1](https://user-images.githubusercontent.com/9432488/110224051-59ba8900-7ea6-11eb-9df6-161412cbc9e5.jpg)

**Comment by ChunkeeMunkee** [comment] 2021-03-10 23:18
Tested several characters in 3.0.0, both travelling to Falkreath and starting in Dead Man's Drink - no issue.

Tested with two caharcters in 3.0.1 (updated today) in same circumstances - one entering Falkreath, one starting in Dead Man's Drink - issues pictured above were found.

**Comment by TwistedModding** [comment] 2021-03-11 01:36
duplicate of #232 and this one doesnt have needed info so we'll use the other one

**Closed by TwistedModding** 2021-03-11 01:36 UTC
Labels: Dev Team, Moderate Bug
