### ISSUE TITLE
CTD due to body paints in character creation

### ISSUE THREAD

**Issue by Cat656** [ForgottenGlory/Living-Skyrim-3#8] opened 2021-02-01 15:50 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Version 2/1/2021 3.0.0.1 Beta 1

**Describe the bug**
A crash to desktop when a body paint is selected as female high elf. I can't easily find it as hovering over it crashes, but it is shortly under crags

**To Reproduce**
1. Create a new save
2. Select a female high elf
3. Go to body paint tab
4. In select texture, have your mouse hovering over the list when you try to go past crag styles

**Expected behavior**
I would be shown either a new body paint or no paint, instead of a CTD.

No save, as this is still in character creation. Also nothing in the overwrite file.

**Comment by ForgottenGlory** [comment] 2021-02-01 16:12
Duplicate of #7

**Closed by ForgottenGlory** 2021-02-01 16:12 UTC
Labels: Dev Team, New Bug
