### ISSUE TITLE
Mogo's Mead

### ISSUE THREAD

**Issue by JulesMarz** [ForgottenGlory/Living-Skyrim-3#648] opened 2022-01-31 20:23 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7.1

**Describe the bug**
Mogo's Mead - No mead to take from Blackbriar brewery

**To Reproduce**

**Expected behavior**
I think I'm supposed to swap some mead here. 

**Screenshots**
![enb2022_1_31_20_01_17](https://user-images.githubusercontent.com/40864686/151867124-0db5e766-6377-4c07-b1c1-3d3441dfef45.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment] 2022-02-01 01:51
Duplicate of #605 with less info.

**Closed as completed by celadoneiron** 2022-02-01 01:51 UTC
Labels: New Bug
