### ISSUE TITLE
Some npcs have black facial texture

### ISSUE THREAD

**Issue by Ayyeitsjoshh** [ForgottenGlory/Living-Skyrim-3#127] opened 2021-02-12 08:51 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3/beta 3/map update

**Describe the bug**
Forsworn and several other npcs faces are black

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without th
![20210211213901_1](https://user-images.githubusercontent.com/59943433/107747505-5cbdc180-6ccc-11eb-925e-97017f3a9fe9.jpg)
is will be closed.

**Additional context**

**Comment by celadoneiron** [comment] 2021-02-12 11:15
Related to but not a duplicate of #32 . This happens because the folder name for facegeom associated with the OrganicFactionsExtension.esp has been renamed to refer to ...\OrganicFactionsExtension.esm. The folders for OrganicFactions.esm still end in .esp.

The correct folder names are:


Data\textures\actors\character\facegendata\facetint\OrganicFactions.es**m**
Data\meshes\actors\character\facegendata\facegeom\OrganicFactions.es**m**

Data\textures\actors\character\facegendata\facetint\OrganicFactionsExtension.es**p**
Data\meshes\actors\character\facegendata\facegeom\OrganicFactionsExtension.es**p**

**Comment by ForgottenGlory** [comment] 2021-02-21 07:16
Fixed Beta 4

**Closed by ForgottenGlory** 2021-02-21 07:16 UTC
Labels: Dev Team, Minor Bug
