### ISSUE TITLE
Purple bark trees

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#54] opened 2021-02-04 05:32 UTC
*LS Version**
3

**Describe the bug**
While adventuring, I came across some tree in the distance with purple trunks.

**To Reproduce**
Face east towards Kynesgrove

**Expected behavior**
Tree's bark is brown

**Screenshots**
![ScreenShot175](https://user-images.githubusercontent.com/57841662/106849224-2e563b80-6667-11eb-9fc7-22385198a626.png)
![ScreenShot176](https://user-images.githubusercontent.com/57841662/106849248-37dfa380-6667-11eb-80ad-84f42e5006b8.png)

**Additional context**
[Crash.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5923396/Crash.zip)

**Comment by ForgottenGlory** [comment] 2021-02-04 05:35
Duplicate of #9

**Closed by ForgottenGlory** 2021-02-04 05:35 UTC
Labels: Dev Team, New Bug
