### ISSUE TITLE
Body parts like hands and/or torso are invisible when crafting or readying a weapon/spell

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#14] opened 2021-02-01 20:40 UTC
**LS Version**
3

**Describe the bug**
When I started in my home (Breezewood in Riverwood) and was at the crafting table, my torso and arms were invisible. Whenever I raise my hands, the arms are invisible.

**To Reproduce**
Raise arms

**Expected behavior**
Arms and whole body is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/57841662/106515212-3442f580-648a-11eb-864b-110bd12fe5b3.png)
![Head but no body or hands](https://user-images.githubusercontent.com/57841662/106515246-3f962100-648a-11eb-86c9-917668dd91b0.png)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5906644/saves.zip)

**Additional context**
This issue has been happening sense I started playing. The zip file is from my latest save.

**Comment by Quietbeat** [comment] 2021-02-02 00:39
I have the Hedge Armour Set and from another post, the armor might be the culprit.

**Comment by ForgottenGlory** [comment] 2021-02-02 04:12
Duplicate of #6

**Closed by ForgottenGlory** 2021-02-02 04:12 UTC
Labels: Dev Team, New Bug
