### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#78] opened 2021-02-07 03:32 UTC
[Crash_2021_2_6_19-28-39.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5938207/Crash_2021_2_6_19-28-39.txt)

**LS Version**
3

**Describe the bug**
I was doing the quest where after entering Helgen for the first time, you check the corpse and either go to the cave or to Whiterun. When UI entered the cave the game crashed.

**To Reproduce**

1. Get the quest to explore Helgen for the first time, 
2. Check the corpse and read the book
3. Go to the cave 

**Expected behavior**
The game doesn't crash

**Screenshots**
N/A

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5938210/saves.zip)

**Comment by daffodilian** [comment] 2021-02-07 04:05
Hi, were you able to continue the quest after relaunching the game? Or was this crash repeating?

**Comment by Quietbeat** [comment] 2021-02-07 15:47
Hi, I was able to continue after restarting the game. I checked my anti-virus (Avast Premium Security) and there are no alerts.

**Comment by TwistedModding** [comment] 2021-02-07 17:31
Since you weren't able to reproduce it, I'm going to close this report.

**Comment by TwistedModding** [comment] 2021-02-07 17:34
For the future, don't report crashes unless they are reproducible. Thank you.

**Closed by TwistedModding** 2021-02-07 17:34 UTC
Labels: Dev Team, New Bug
