### ISSUE TITLE
Constant CTDs anytime I save the game, fast travel, enter a new location or respawn

### ISSUE THREAD

**Issue by adam024** [ForgottenGlory/Living-Skyrim-3#352] opened 2021-05-17 04:56 UTC
LS Version
3.2.0

Describe the bug 
I first encountered the bug during "The Black Star" quest, near the end of ilinalta's deep. Now everytime I save the game or enter a new location, the game crashes to desktop. I had about 30 hours in my save before this started happening. I tried a full reinstall of the modlist, but that did not fix the issue.

To Reproduce 
The issue seems to occur anytime I save the game, no matter where I am on the map.

Expected behavior 
No crash.

Screenshots
None.

[Last save before issue occured.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6491194/Last.save.before.issue.occured.zip)

[Crash_2021_5_17_0-15-31.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6491196/Crash_2021_5_17_0-15-31.txt)
[Crash_2021_5_17_0-23-3.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6491197/Crash_2021_5_17_0-23-3.txt)
[Crash_2021_5_16_23-55-2.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6491195/Crash_2021_5_16_23-55-2.txt)

**Comment by ForgottenGlory** [comment] 2021-05-17 12:30
Duplicate of #343

**Closed as completed by ForgottenGlory** 2021-05-17 12:30 UTC
